version: '2.2'
services:
  web:
    image: orangehrm/orangehrm-environment-images:uat-7.4-ubuntu-20.04
    ports:
      - "7474:443"
      - "2992:22"
    volumes:
    - ./html:/var/www/html
    - ./home:/home
    - ./config/security/access.conf:/etc/security/access.conf
    - ./config/resolve-permission.sh:/etc/resolve-permission.sh
    - ./config/resolve.conf:/etc/resolve.conf
    - ./config/mysql-client:/etc/mysql
    - ./config/apache2/sites-available:/etc/httpd/sites-enabled
    - ./config/apache2/cert:/etc/httpd/cert
    - ./config/apache2/ssl.conf:/etc/httpd/conf.d/ssl.conf
    - ./logs/ubuntu_logs:/var/log/httpd
    - /etc/localtime:/etc/localtime
    - ./config/hostname:/etc/hostname
    - ./config/welcome:/etc/motd
    - ./config/sudoers:/etc/sudoers
    - ./config/sssd/sssd.conf:/etc/sssd/sssd.conf
    - ./config/crontabs:/var/spool/cron/crontabs
    - ./config/ssh/sshd_config:/etc/ssh/sshd_config
    - ./config/ldap/cert:/etc/openldap/cacerts
    - ./config/ldap/sudo-ldap.conf:/etc/sudo-ldap.conf
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tty: true
    privileged: true
    restart: always
    hostname: bishop-server
    container_name: bishop_web
